### PR TITLE
Add support for passing an extra env object to the MarkdownSerializer

### PR DESCRIPTION
**Pull request by segevfiner**
Similar to the env passable to markdown-it parse

### CODE REVIEW

**Comment by marijnh** [comment]
What is the intended use of this?

**Comment by segevfiner** [comment]
I don't understand what do you suggest that Indo instead...

**Comment by marijnh** [comment]
Something like this (or, more crudely, just set a global):

```javascript
let env = null
function withEnv(_env, f) {
  let prev = env
   env = _env
  try { return f() }
  finally { env = prev }
}
```

**Comment by segevfiner** [comment]
That doesn't feel like a very safe way of doing it...

**Pull request closed without merging**
