### PR TITLE
Avoid escaping underscores within urls

### PR DESCRIPTION
**Pull request by mstijak**
This solves #65. It's ugly, but this is the best I could.

### CODE REVIEW

**Comment by marijnh** [comment]
There's not need to recognize URLs -- underscores in words like `foo_bar_baz` also don't get picked up by Markdown (see [the spec](https://spec.commonmark.org/0.30/#emphasis-and-strong-emphasis)). When there are word characters around a run of underscores, you can leave them unescaped.

**Comment by mstijak** [comment]
What about an underscore at the end?
```
https://example.com/abc_
```

**Comment by marijnh** [comment]
That can cause italics (see [here](https://spec.commonmark.org/dingus/?text=_https%3A%2F%2Fexample.com%2Fabc_))

**Comment by marijnh** [comment]
That's not really weird—the first and last underscore are not surrounded by word characters, and thus unambiguously indicate italics in Markdown notation. But in practice, I think avoiding escaping underscores between word characters will fix a lot of the problematic situations.

**Comment by mstijak** [comment]
I made another PR.

**Comment by duhaime** [comment]
@mstijak do you have a link to the other PR?

**Comment by mstijak** [comment]
@duhaime Sure, it's https://github.com/ProseMirror/prosemirror-markdown/pull/67.

**Pull request closed without merging**
